create table employee(
                         id int generated by default as identity primary key,
                         lastName varchar(50) not null,
                         firstName varchar(50) not null,
                         surName varchar(50) not null
);
create table trips(
                      id int generated by default as identity primary key,
                      tripCost numeric(10, 2) not null,
                      employeeId int references employee(id),
                      routesId int references routes(id),
                      departureTime date not null,
                      arrivalDate date not null,
                      touristCount int not null,
                      penaltySize numeric(10, 2) not null
);
create table routes(
                       id int generated by default as identity primary key,
                       countryId int references country(id),
                       routeName varchar(100) not null,
                       duration int not null
);
create table country(
                        id int generated by default as identity primary key,
                        countryName varchar(100) not null
);

create table routeByPoints(
                              id int generated by default as identity primary key,
                              routeId int references routes(id),
                              routePointsId int references routePoints(id)
);
create table groupTourist(
                             id int generated by default as identity primary key,
                             tripsId int references trips(id),
                             clientId int references clients(id)
);
create table clients(
                        id int generated by default as identity primary key,
                        lastName varchar(50) not null,
                        firstName varchar(50) not null,
                        surName varchar(50) not null,
                        dateOfBirth date not null,
                        passportSeries varchar(4) not null,
                        passportNumber varchar(6) not null,
                        dateOfIssue date not null,
                        issuedBy varchar(100) not null,
                        photo varchar(400) not null
);
create table routePoints(
                            id int generated by default as identity primary key,
                            excursionProgramId int references excursionProgram(id),
                            cityId int references city(id),
                            hotelId int references hotel(id),
                            routeName varchar(100) not null,
                            durationAtPoint int not null
);
create table excursionProgram(
                                 id int generated by default as identity primary key,
                                 excursionProgramName varchar(400)
);
create table city(
                     id int generated by default as identity primary key,
                     hotelId int references hotel(id),
                     excursionProgramId int references excursionProgram(id),
                     cityName varchar(100) not null
);
create table hotel(
                      id int generated by default as identity primary key,
                      hotelName varchar(100) not null,
                      hotelClass int not null
);

